services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  spring-app:
    image: openjdk:21-jdk-slim
    container_name: spring-boot
    working_dir: /app
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    command: >
      bash -c "
        cd /app &&
        chmod +x mvnw &&
        ./mvnw spring-boot:run -Dspring-boot.devtools.restart.enabled=true
      "
    ports:
      - "${SPRING_APP_PORT}:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      SPRING_PROFILES_ACTIVE: DEV
      SPRING_FLYWAY_LOCATIONS: filesystem:migrations
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_ACCESS_EXPIRATION_SECONDS: ${JWT_ACCESS_EXPIRATION_SECONDS}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      JWT_REFRESH_EXPIRATION_SECONDS: ${JWT_REFRESH_EXPIRATION_SECONDS}
      JWT_COOKIE_SAME_SITE: None
      CORS_ALLOWED_ORIGINS: http://localhost:3000
      WEB_APPLICATION_URL: http://localhost:3000/
    develop:
      watch:
        - path: ./src
          target: /app/src
          action: sync
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql-data:
