name: Deployment In-Progress Check

on:
  pull_request:
    branches:
      - main

jobs:
  main-branch-deployment-status-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check for running workflows on main
        run: |
          # Get running workflows on main branch
          running_workflows=$(curl -s \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs?branch=main&status=in_progress" \
            | jq -r '.workflow_runs[] | select(.name != "Check Main Branch Status") | .html_url')
          
          if [ ! -z "$running_workflows" ]; then
            echo "Error: There are currently running workflows on main branch:"
            echo "$running_workflows"
            echo "Please wait for them to complete before merging, and then re-run the workflow."
            exit 1
          fi
          
          echo "Main branch is clear for merging"