name: Migration Order Validation

on:
  pull_request:
    branches:
      - main
    paths:
      - 'migrations/*.sql'

jobs:
  validate_migration_order:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get latest migration from main branch
        id: main-migration
        run: |
          git fetch origin main
          # Properly piped commands to sort and get the latest migration
          LATEST_MAIN=$(git ls-tree -r origin/main migrations/ | grep '\.sql$' | awk '{print $4}' | sort -V | tail -n 1)
          MAIN_TIMESTAMP=$(echo "$LATEST_MAIN" | grep -oE 'V[0-9]{4}_[0-9]{2}_[0-9]{2}_[0-9]{6}' | sed 's/V//' | tr -d '_')
          echo "main_timestamp=$MAIN_TIMESTAMP" >> $GITHUB_OUTPUT
          echo "Latest main migration: $LATEST_MAIN"

      - name: Check PR migrations
        run: |
          MAIN_TIMESTAMP="${{ steps.main-migration.outputs.main_timestamp }}"
          
          # Get list of changed migration files in PR
          PR_MIGRATIONS=$(git diff --name-only origin/main... migrations/ | grep '\.sql$' || true)
          
          # Check each migration file in PR
          for migration in $PR_MIGRATIONS; do
            MIGRATION_TIMESTAMP=$(echo "$migration" | grep -oE 'V[0-9]{4}_[0-9]{2}_[0-9]{2}_[0-9]{6}' | sed 's/V//' | tr -d '_')
          
            if [ -z "$MIGRATION_TIMESTAMP" ]; then
              echo "Error: Migration file $migration does not follow naming convention VYYYY_MM_DD_HHMMSS.sql"
              exit 1
            fi
          
            if [ "$MIGRATION_TIMESTAMP" -le "$MAIN_TIMESTAMP" ]; then
              echo "Error: Migration $migration is more order than or equal to the latest migration in main branch"
              echo "PR Migration timestamp: $MIGRATION_TIMESTAMP"
              echo "Latest main branch migration timestamp: $MAIN_TIMESTAMP"
              exit 1
            fi
          done
          
          echo "All migrations are newer than the latest migration in main branch"
