name: CI/CD Pipeline

on:
  push:
    branches:
      - '*'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: project_db
          MYSQL_USER: username
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v1

      - name: Build and run tests in Docker
        env:
          SPRING_APP_PORT: 8080
          MYSQL_DATABASE: project_db
          MYSQL_USER: username
          MYSQL_PASSWORD: password
        run: |
          docker build -t spring-app-test -f Dockerfile.pipeline .
          docker run --rm \
            --network host \
            -e SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/project_db \
            -e SPRING_DATASOURCE_USERNAME=username \
            -e SPRING_DATASOURCE_PASSWORD=password \
            -e SPRING_PROFILES_ACTIVE=TEST \
            -e SPRING_FLYWAY_LOCATIONS=filesystem:migrations \
            spring-app-test \
            ./mvnw test